---
title: "Syllabus | Advanced GIS Analysis and Programming"
author: "Center for Geospatial Analysis"
date: "Fall 2021"
---

****

Course Description
==================

This course extends the existing base of GIS knowledge and skills by amplifying programmatic approaches to spatial data and analysis.
Lectures, labs and projects emphasize GIS model development, spatial database architecture and design best practices, and extend knowledge of web GIS by authoring and consuming geographic web services.
Students will become familiar with methods of leveraging programming languages (such as Python) to make GIS processing easier, faster and more accurate by scripting and automating data management, production, manipulation and analysis procedures.
Activities develop GIS analysis skills with examples from government, social science, physical science and the humanities.

Catalog Number
:   - GIS 420/520
    - Section 1
    - CRN 14652/16164

Prerequisites
:   - BIOL 445 "GIS for Biologists" or GIS 201/INTR 204 "Introduction to Geographic Information Systems and Spatial Analysis"

Semester
:   - Fall 2021 (2021-Sep-01 to 2021-Dec-21)

Location
:   - [Swem Library](https://www.wm.edu/about/visiting/campusmap/location/swem.php), Rm 215

Class Times
:   - Tuesday, Thursday
    - 11:00-12:20

Instructor
:   - Dr. Tyler W. Davis
    - Email: twdavis@wm.edu
    - Physical Office: [Center for Geospatial Analysis](https://www.wm.edu/as/cga/), Swem Library Rm 213
    - Virtual Office: [Nooks](https://nooks.in/goto/7cc0KabvZpnfVKyV?pwd=o162Tu)
    - Phone: 757-221-6449
    - Websites:
        - https://drdavis.space
        - https://cga-wm.github.io/

Office Hours
:   - Mo. & We. 1200--1300; Th. 0930--1030
    - Also by appointment
    - *Appointments are welcome outside normally scheduled office hours; please message or email to set up a time.*
    - *There may be certain days when office hours will be either canceled or rescheduled; notifications will be sent ahead of time.*

Delivery
:   - This lecture/lab class has a labeled modality of __FS__, which means that it meets predominantly in person (face-to-face) and predominantly synchronous (all meet at the same scheduled place at the same scheduled time).

Final Exam
:   - Written/oral evaluation on or before COB Monday, 20 December 2021

Minimum Passing Grade

:   - D

Communication

:   - Instant messaging using [GroupMe](https://groupme.com/)
        - For instant delivery of content or for questions that need quick responses.
        - *Please email me your preferred GroupMe email address or use the join link below*
        - Join Link: https://groupme.com/join_group/69693978/Fe5J6QsW
    - Discussion posts, Q&A, and schedule management using [GitHub](https://github.com/cga-wm/advgis-echo)
        - For weekly engagement including sharing ideas, methods and content and asking/responding to questions, comments or concerns.
        - This will serve as a primary hub; all other content will be linked from here.
        - *Please create a GitHub account and send your username to your professor*
    - Video conferencing (e.g, [Zoom](https://cwm.zoom.us/) or [Nooks](https://nooks.in/goto/7cc0KabvZpnfVKyV?pwd=o162Tu))
        - Video conferencing is for office hours, video chats, conference meetings and oral evaluations where "face-to-face" communication or screen sharing is required.
        - If one of these options doesn't work for you, please let me know and I'll work with you on finding a suitable alternative.
        - *Please note that Nooks presently does not support mobile devices or Safari web browser :(*
    - Evaluation using Google Docs
        - *Please be sure to share with edit permissions your Performance Accomplishments document*
    - ArcGIS Notebooks and item sharing on [ArcGIS Online](https://www.arcgis.com/index.html)
        - _Please be sure to log into [arcgis.com](https://www.arcgis.com/index.html) using the W&M organization URL: **wm-gis**.maps.arcgis.com (see [here](https://youtu.be/x07Xyoe0d2k) for instructions)_
        - *You will be added to the AdvGIS group*
    - Email ([twdavis-at-wm-dot-edu](mailto:twdavis@wm.edu))
        - The new snail mail; use this for personal communication or whenever sharing is inappropriate.
    - Website blog (https://cga-wm.github.io/course/adv-gis/blog.html)
        - Maintained by your instructor for communicating ideas, methods and course content.

    See [**Code of Conduct**](#the-code-of-conduct) regarding how these communication platforms are (and should be) used.

Textbook
:   - Today's GIS text is the World Wide Web itself
    - The following are some helpful web resources:
        - https://cga-wm.github.io/ (*see Resources*)
        - https://cga-wm.github.io/course/intro/ (*see Chapters and Resources*)
        - https://doc.arcgis.com/en/
        - https://www.esri.com/training/ (*see Course Catalog*)
        - https://developers.arcgis.com/labs/ (*see Tutorials*)
        - https://learn.arcgis.com/en/ (*see Lesson Gallery*)
        - [CGA GIS Tutorial YouTube Playlist](https://www.youtube.com/playlist?list=PLiOhBg8WdMaLx_cg5FmBEA0hUvnrsplKl)
        - [Advanced GIS Workflow Playlist](https://youtube.com/playlist?list=PLbIkNQKCuzMPSwHHGZ4nFncmlw52l57fv)
        - [Advanced GIS Geocoding Playlist](https://youtube.com/playlist?list=PLbIkNQKCuzMOSgHamvzS0KaEGaJ3goke1)

Course Materials
:   - Laptop or desktop computer (*recommended*)

        \* _Your computer should have at least 500 MB of free disk space, have at least 8 GB of memory, and run a modern desktop OS (e.g,. PC, Mac, or Linux); netbooks need not apply._
    - Dedicated USB 3.0 thumb drive 64 GB or larger (*recommended*)

        \* _Organizing your data and maintaining a backup can save you from serious misfortune; I know from experience._

Technology
:   - Geospatial visualizations and analysis may be handled using any of the following:
        - The latest stable release or the university's current installed versions of Esri's [ArcGIS Pro](https://www.esri.com/en-us/arcgis/products/arcgis-pro/resources) or [ArcMap](https://www.esri.com/en-us/arcgis/products/arcgis-desktop/resources)

            \* _ArcGIS Pro may be installed on individual computers for Microsoft Windows users only (see [here](https://www.wm.edu/as/cga/resources/software/index.php) for instructions)._
            _ArcGIS Pro may also be accessed via the W&M Virtual Desktop Infrastructure on Windows (see [here](https://youtu.be/pZh-fMoaV54)) or on Mac (see [here](https://youtu.be/lG43GtH1Ta4))._

            \* _ArcMap (a part of ArcGIS Desktop) is being phased out of use._
            _If GIS is in your future, you may wish to consider migrating to ArcGIS Pro._
        - The latest stable release or the university's current installed version of [QGIS Desktop](https://www.qgis.org/en/site/)

            \* _QGIS may be downloaded and installed on all major OS's (see [here](https://www.qgis.org/en/site/) for instructions)._
            _QGIS may also be accessed via the W&M Virtual Desktop Infrastructure on Windows (see [here](https://youtu.be/pZh-fMoaV54)) or on Mac (see [here](https://youtu.be/lG43GtH1Ta4))._
        - [ArcGIS Online](https://www.arcgis.com) (*see [here](https://youtu.be/x07Xyoe0d2k) for login instructions*).
    - Programming and analysis may be handled using either [ArcGIS Notebooks](https://www.esri.com/en-us/arcgis/products/arcgis-notebooks/overview) on the Portal or in ArcGIS Pro (v.2.5 or above).

        \* _The ArcGIS Notebook is a cloud-based integrated development environment built for processing, analyzing and visualizing geospatial data._
        _You will be granted access to Notebooks through ArcGIS Online._
        _Notebooks provide you with all the geoprocessing tools of ArcPro and ArcGIS without having to install any software on your computer._
        _Mac users, rejoice!_
        _You also have access to ArcGIS Notebooks through [ArcGIS Pro](https://www.esri.com/arcgis-blog/products/arcgis-pro/analytics/introducing-arcgis-notebooks-in-arcgis-pro/) (v 2.5 and greater)._
    - Remote access to W&M computing services are handled using the Virtual Desktop Infrastructure, which may be accessed on Windows (see [here](https://youtu.be/pZh-fMoaV54)) or on Mac (see [here](https://youtu.be/lG43GtH1Ta4)).

---

Course Objectives
=================
1. Apply geospatial problem-solving tactics through individual and collaborative research, design and analysis to real-world challenges.
    - *Achieved through the client meeting and special works projects.*
2. Define geoethics and evaluate it with regards to a real-world scenario.
    - *See items in the* **Become More Geoethical** *section of the master checklist.*
3. Develop new learning, time management and data organization skills.
    - *Skill development through tutorials, videos, research, collaborations, etc.*
    - *Time management through weekly reports and scheduled meetings.*
    - *Data organization through proper metadata and file geodatabase design.*
4. Demonstrate professional communication skills for reaching broad audiences.
    - *Through web presence, audio/video presentations, discussion board responses, and client meeting.*
5. Develop programming skills for geospatial applications.
    - *Through ModelBuilder, ArcGIS Notebooks and ArcGIS for Developers tutorials.*


What you should already know
----------------------------
* You should have a basic understanding of the main two geographic data models (vector and raster), including: what they represent; how these data models are created, stored, and edited; the pros and cons of these two data models; and how to open, manipulate and visualize them using a GIS.
* You should have a basic understanding of geographic coordinate systems, including: the main components of coordinate systems, how to perform projections and transformations of geographic data, and what it means to do so.
* You should have a basic understanding of the GIS project workflow, including: finding and creating spatial data; managing data files and their metadata; designing a workflow of geoprocesses to meet an intended goal; and visualizing spatial data (and/or products) in a meaningful way.

What is expected of you
-----------------------
* Work both collaboratively and individually on completing course tutorials, exercises and special works projects.
* Create a fictitious consultancy responsible for:
    - evaluating the reproducibility of a real-world geospatial problem of your choice (pending instructor approval);
    - building a public-facing website that includes a summary of the project, an evaluation of geoethics, and a blog of milestones / accomplishments
    - providing at least two methodologies for solving at least one special works problem;
    - creating and disseminating a novel dataset in at least two file formats (e.g., file geodatabase and GeoJSON)
    - scheduling a "client" meeting to review the progress of the reproducibility project
* Maintain a weekly log/report posted on the course repository's wiki that outlines *everything* you do for this class (including any research, development, analysis, and collaboration) and approximately how long it took you to do it.

    > The First Step Towards Effectiveness by Peter E. Drucker
    >
    > 1. Know thy time.

* Communicate with your classmates and instructor using remote/web-based technology (see **Communication** above).
    This includes contributing to the weekly discussion topics.
* Ask questions and make mistakes.
    If you are feeling frustrated, then you are likely invested in this class.
* Uphold professionalism in everything you do (see [**Code of Conduct**](#the-code-of-conduct) below).
* Provide a course evaluation at the end of the term with a summary of things you liked and disliked; methods that worked for you and those that fell short; topics that interested you and those that were uninteresting.

**GIS 520 Students only**

* Complete a performance accomplishments document that summarizes the work done in this class that satisfies the learning objectives (see [Course Objectives](#course-objectives) above).
* Schedule and meet with your instructor a minimum of three times:
    1. On or before the end of week 3 (17 September) to overview the expectations for the Performance Accomplishments;
    2. On or before the end of week 8 (22 October) to report on your progress; and
    3. On or before the end of finals (20 December) for the oral evaluation of your performance accomplishments.


What to expect from your instructor
-----------------------------------
* Manage all web resources
* Introduce/explain concepts and guide you through demos
* Provide links to tutorials and other helpful guides
* Answer questions and provide feedback as requested through email, chat, discussion board forums, weekly reports or other means in a timely manner
* Make accommodations for meeting requests during and/or outside scheduled office hours

---

Course Structure
================

How this class is stylized
--------------------------
Originally, I designed this course to mimic a real-world geospatial organization that solves spatial problems; therefore, a large focus of this class will be presenting you with challenge questions and asking you to solve them.
To build your geospatial problem-solving skills, we will tackle these challenges together, sharing our methods and results with one another.
I will show you tips and tricks and introduce you to new GIS methods and tools to help you become better, faster and stronger GIS professionals.

For this class, I took inspiration from Ben Balter's ["15 rules for communicating at GitHub"](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/).
This type of asynchronous workstyle is becoming more prevalent and economically gainful in today's tech world; not to mention the accelerated rate of remote work under the present pandemic.
Having the skills to work remotely and collaboratively can give you a "leg up" in the job market.
This course aims to pair style with content to give you a truly advanced geospatial analysis and programming experience.

Your goal is to work both individually and as a team to address (and potentially solve) the various projects that are assigned.
For all projects, you choose how to address them.
You keep in constant communication with your classmates and instructor, build off of each other's strengths, share ideas and methods, and create new ways of efficiently solving geospatial challenges.

This style of learning closely resembles what will be expected of you following graduation and entering the workforce.
The difference here is that there is the expectation that you will help one another (not always the case in the real world) and your instructor will be your personal tutor and guide (a luxury, for certain).

> **Disclaimer 1**: This class is a part of the Center for Geospatial Analysis's [Certificate in Geographic Information Science Program](https://www.wm.edu/as/cga/certificate/overview/index.php) and is offered to post-baccalaureate level students.
> Undergraduates at William & Mary also have the opportunity to take this course with slightly modified expectations during evaluation.


> **Disclaimer 2**: In academia, it is well known that new courses take about 4--6 iterations before they are "well developed."
> That being said, this class is currently in "echo" version (i.e., fifth iteration); therefore, two things apply: 1) class structure, methods, topics, delivery, evaluation, etc. are in a constant state of change so please be patient; 2) you are in a position to alter the course by providing feedback, so please, in your personal notes, jot down your thoughts, opinions and concerns regarding the class as we go along; you may use this to craft your course evaluation at the end of the term.

How class time is used
----------------------
This class is scheduled to meet twice a week.
The goal is to have one class session each week dedicated to discussions (e.g., topics of the week, consultancy issues and concerns, etc.).
The other day each week should be the instructor introducing topics, skills, or methods relevant to the class.
See the posted [course calendar](https://cga-wm.github.io/course/adv-gis/calendar.html) for tentative schedule.

This is an advanced class aimed at introducing several new concepts, software, tools, methods, and analyses.
It is strongly suggested (and even required) that you take advantage of one another and the instructor to maximize what can be done and what you can learn during this time.

Remember, your goal is to complete the Master Checklist (and, if you are a certificate student, the Performance Accomplishments write up) before the end of term.
To do so, you need to demonstrate that you have satisfied the [learning objectives](#course-objectives) for this course.


How this class is assessed
--------------------------

### Certificate Level (GIS 520)
_This class is assessed based on a written/oral evaluation of student learning._

You will schedule a one-on-one final evaluation with your instructor following at least two individual meetings (one at the beginning and one in the middle of the semester).

You grade is based on your demonstration of your mastery of the course objectives.
You are solely responsible for communicating what you have done to succeed in each of these categories.
This is accomplished by the following:

1. Positive, productive engagement as demonstrated by weekly discussions, weekly reports, and communication with the class (e.g., usage of GitHub Issues, GroupMe chat, email, etc.).
1. Successful and professional client meeting.
   Please be aware that I am debriefed on how your meeting went by the CGA Fellows.
1. Accomplishments write up and completion of the master checklist.
    - You are solely responsible for communicating what you have done this semester and how it contributes to the course's learning objectives.
    - That being said, I have created the master checklist and tips/suggestions in the performance accomplishments to help and guide you with this process.
1. Final evaluation.
    - Successfully complete two (2) special works projects: one written (and/or video recorded) and one demonstrated live (either during the last weeks of class or one-on-one during the final evaluation).
    - Successfully answer a series of GIS-related questions.

Based on the cumulative assessment of individual accomplishments, a student will earn the corresponding grade for their level of achievement.

Qualitative Assessment | Approximate Grade | Meaning |
:--- | :--- | :------ |
Unsatisfactory | F | Demonstrates a lack of effort, lack of care, and/or lack of understanding the course objectives. |
Does Not Meet Expectations | C--, D+, or D | Demonstrates a lack of understanding of one or more course objectives. |
Fully Meets Expectations | B, B--, C+, or C | Demonstrates a basic understanding of the course objectives. |
Exceeds Expectations | A, A--, or B+ | Demonstrates exceptional understanding of the course objectives. |

The following stipulations impact a student's final grade and are evaluated in the following order.

* A single "Unsatisfactory" evaluation results in an overall "Unsatisfactory" grade
* Any given task (A--D) consisting entirely of "Does Not Meet" or a total of nine (9) or more evaluations as "Does Not Meet" across tasks results in an overall "Unsatisfactory" grade
* More than 4 "Does Not Meet" evaluations results in an overall "Does Not Meet Expectations" grade
* Three (3) or more  tasks consisting entirely of "Exceeds" or a total of eleven (11) or more evaluations as "Exceeds" results in an overall "Exceeds Expectations" grade
* All other grades fall into the "Fully Meets Expectations" category

The instructor reserves the right to adjust a student's final evaluation score by at most one-half step (e.g., in a plus/minus scale, a C may be rewarded to a C+ or downgraded to a C--) so long as it does not conflict with the following rules.

* A student cannot receive a final grade higher than Unsatisfactory (F) if they receive an Unsatisfactory evaluation.
* A student cannot receive a final grade less than Does Not Meet Expectations (D) if they did not receive an Unsatisfactory evaluation based on the criteria above.

There are no points, bonuses or extra credit assignments awarded at the certificate level (GIS 520) of this class.

### Undergraduate Level (GIS 420)
_This class is assessed based on the completion of course tasks (master checklist) and final evaluation of student learning (written exam)._

On the course repository, there is a master checklist of over 100 tasks (dismissing any tasks labeled _GIS 520 only_).
Undergraduate students are awarded 1 point for each completed task (checked item) on their master checklist.

The undergraduate final exam will be administered during the final exam period (see the registrar's [online schedule](https://www.wm.edu/offices/registrar/calendarsandexams/examschedules/fall21exam/index.php#class)).
The final exam is comprised of five questions.
Each question completed successfully contributes 1 point to a student's final grade.
Each question not answered (or answered unsuccessfully) deducts two points from a student's final grade.

An undergraduate student's final grade is the summation of their total points (checked items) from the master checklist with their score on the final exam.
An undergraduate student's final letter grade is determined based on the values in the following table.

----------------------
Letter     Point Score
------  --------------
A               >93.0

A--       90.0--92.99

B+        87.0--89.99

B         83.0--86.99

B--       80.0--82.99

C+        77.0--79.99

C         73.0--76.99

C--       70.0--72.99

D+        67.0--69.99

D         60.0--66.99

F               <60.0
---------------------------------------------------

> There is no expectation that students can or will complete all tasks on the master checklist; however, students who keep pace with the instructor can and should be able to complete a sufficient number of items to both successfully complete the class and pass the final exam.

There are no bonus points nor extra credit awarded at the undergraduate level (GIS 420) of this class.
Final scores are based on the level of completion of the master checklist and evaluation of the final exam responses as of COB on Monday, 20 December 2021.
No further adjustments can be made following the final exam period.

---

# Course Topics
The following are a list of topics that may covered during the term.


* GIS Specialists versus Developers
* Geoethics
* GIS workflows and design
* Geocoding, geofencing and other geoprocesses
* Markdown text formatting
* Python programming language
* Arcade expression language
* Programmatic approaches to managing geospatial data
* Programmatic approaches to solving geospatial problems

---

Course Calendar
===============
This semester, each week will consist of at least five discussion topics, potential readings and responses, and a weekly write-up.


Important Dates
---------------
First day of term
:   - 1 September 2021

Add/drop deadline
:   - 10 September 2021

Fall break
:   - 16--19 October 2021

Withdraw deadline
:   - 1 November 2021

Last day of term
:   - 10 December 2021

Day of final exam
:   - 20 December 2021

---

Standards & Policies
====================

The Code of Conduct
-------------------
By the basis in which this class is designed, these things hold true:

1. This class utilizes several forms of communication (e.g., instant messaging, discussion boards, emails, audio/video conferencing), of which not all can be monitored by the instructor at all times.
2. You are responsible for how you interact with each other.

Remember these things as you work together:

1. "Don't ascribe maliciousness to that which can be explained by inadvertence."

    This comes from the fact that it is almost impossible to portray our feelings or intended meaning behind typed text.
    If something offends you, take a breath, be cordial and ask for clarification before unleashing your wrath (BTW: you shouldn't unleash your wrath).
    That being said, also do not be a silent witness.
    If something offends you, let everyone know.
    We will never learn from our mistakes if our mistakes are never pointed out.
    If malicious actions continue, the instructor will manage it.
2. "There is no innovation and creativity without failure. Period."

    You are a college student registered in a college class.
    You are not expected to know everything.
    The entire purpose of this exercise is for you to gain knowledge, so make an effort.
    If you want to try something, try it and let everyone know what you are up to.
    Best case scenario, your innovations spark new insight.
    Worst case scenario, we all learn something from your efforts.
    Remember: there are no right answers to these projects---just creative approaches, innovative designs and happy accidents---so don't be afraid to make a mistake.
    It's better to aim high for something that will make a difference rather than to play it safe with something easy.
3. Ask lots of questions.

    Questions are cheap, so ask a lot of them.
    When asking questions, remember to always strive for clarity.
    If you don't know something or your aren't sure, just ask.
    Sometimes, knowing the right question to ask is just as difficult as finding the answer.
    When you find yourself here, it's okay send up a flare or simply say "I'm lost."
    We will get you back on track.
4. Focus on opportunities.

    Remember: this is not a race and you are not a judge, so don't get caught up with critiquing or competing with each other.
    Provide your opinions and perspectives and then actually take the time to read the opinions and perspectives of others.
    Challenge yourself to see things differently and try things differently.
    Ignore your desire to be correct or to correct someone else and try not to contradict people; they don't like it and biologically it shuts down their ability to see things logically.
5. Document and share everything.

    While it may feel natural to keep your work private, projects really thrive when you document your process publicly.
    By writing things down and sharing them, more people can participate along the way and you might get help on something you didn't even know you needed.
    This leads to more things being documented, which produces a better project roadmap, which leads to better transparency and feedback, which leads to good decision making and faster/better results.

    We cannot manage what we do not measure: so digitize your process!!!
6. Everyone is bound to uphold a policy of respect for their instructor and their peers.
    Students should be open-minded to new ideas and participate in collegiate debate, the sharing of ideas, and the receiving of feedback without defamatory remarks.
    Students should help maintain a healthy learning environment by refraining from negative behavior, such as harmful remarks, quibbling over trivial matters, creating unnecessary debates, or bullying.

    **There is zero tolerance for negative behavior. Failure to uphold this policy will result in punitive action and/or removing the offending student from access to all or part of the class.**


Engagement Policy
-----------------
- *Weekly engagement is expected.*

It is the expectation that all students perform their tasks and coordinate with their teams in pursuit of accomplishing the tasks outlined for this class.

### Removal of a Team Member

Any student (or team member) recorded as being absent (e.g., not responding to instant messages, not replying to emails, and not attending out-of-class meetings) for two or more weeks is eligible to be removed from a team.
The petition to remove a team member from a team need only show the documentation of failed attempts of communication along with dates / times of meetings in an email (with all member's CC'd) or in print with signatures from all other members.
All completed items by the team following the removal of a team member do not count towards the removed team member's accomplishments.

### Planned Absences

Please make any and all planned absences (e.g., field trips, vacations, athletic events) along with any unplanned absences (e.g., illnesses and emergencies) known to your instructor at the earliest possible time.


Coursework Policy
-----------------
- *You are bound by the honor code.*

By accepting admission to the College, you have made a commitment to understand, support, and abide by the [Honor Code](https://www.wm.edu/honor).
**Violations, whether attempted or successful, will result in consequences ranging from a verbal reprimand up to a failing grade for the class**.

Misconduct may include, but is not limited to, the following:

- cheating or using unauthorized materials on assignments
- fabrication, forgery, alteration, or destruction of documents; hacking unauthorized resources; intimidating or bribing peers; improper collaboration or colluding; plagiarizing; or lying in order to obtain academic advantage
- assisting others in misconduct
- attempting misconduct


Instant Messaging Policy
------------------------
- *The instant messaging app should be used for communication that either: (1) needs to reach people quickly or (2) needs a quick response.*

You are free (and encouraged) to create your own GroupMe groups with classmates for better/faster communication.
Do not use the instant messenger for spamming, soliciting or otherwise disrupting the peace.
Be sure to change your notification settings on your mobile device to provide "Do Not Disturb" periods when sleeping or studying.


Email Policy
------------
- *All personal correspondence should be made to the instructor's W&M email address ([see above](#course-syllabus)) and include the class title in the subject line.*

For private inquiries, please email the instructor; the instructor will confirm each email received.
If you do not receive a confirmation message from the instructor within 12 hours of sending, feel free to send a follow-up email.


Make-Up Policy
--------------
- *There are no make-ups or extensions.*

Undergraduate final exam times are final.
All accomplishments are due on or before the final exam period ends.

Evaluation dates for certificate students should be suggested by the student and approved by the instructor.
If, for some reason, you are unable to meet during the scheduled time or turn in your performance accomplishments on time, you may email the professor before the regularly scheduled evaluation date to reschedule it at a mutually convenient time or else receive an unsatisfactory score.

Under the most rare and extraordinary circumstances, students may request an incomplete; the acceptance of which is at the sole discretion of the instructor.


Standards for Submitted Work
--------------------------
- Written (and/or typed) work should be in English and follow, to the best of your abilities, the rules of the English language (see [Strunk & White](https://faculty.washington.edu/heagerty/Courses/b572/public/StrunkWhite.pdf)).
- Written (and/or typed) work should be neat, thorough, legible, and logically organized.
- All submitted work should include your name, date, and description.
- Filenames should be in all lowercase and contain only alphanumeric, underscore, hyphen, and/or period characters.
- Sketches and figures should be drawn using a straight-edge; plots and graphs should be done using a computer, where appropriate.
- Tables, figures and images from online sources should include a citation (including the author/publisher, date created/accessed, and URL).
- All in-text citations and references should be formatted to APA standards unless otherwise indicated.
- Plagiarism will be taken seriously; *if you write something that is not your own original idea or in your own words, then it must be cited!* See [here](https://ctl.yale.edu/writing/using-sources/understanding-and-avoiding-plagiarism) for information on plagiarism and how to avoid it.
- Unless otherwise stated, typed electronic files may be submitted in one of the following acceptable open formats:
    * [Office Open XML Document](https://en.wikipedia.org/wiki/Office_Open_XML) (.docx)
    * [OpenDocument Text](https://en.wikipedia.org/wiki/OpenDocument) (.odt)
    * [Portable Document Format](https://en.wikipedia.org/wiki/PDF) (.pdf)
    * [Markdown](https://en.wikipedia.org/wiki/Markdown) (.md/.Rmd)
    * [Markup](https://en.wikipedia.org/wiki/Markup_language) (.html/.tex)
    * [Plain Text](https://en.wikipedia.org/wiki/Plain_text) (.txt)
- All image files should be saved in either JPEG (.jpg) or PNG (.png) format.


---

Statements and Resources
========================

ADA Statement
-------------
William & Mary accommodates students with disabilities in accordance with federal laws and university policy.
Any student who feels they may need an accommodation based on the impact of a learning, psychiatric, physical, or chronic health diagnosis should contact Student Accessibility Services staff at 757-221-2512 or at sas@wm.edu to determine if accommodations are warranted and to obtain an official letter of accommodation.
For more information, please see https://www.wm.edu/sas.


Copyright Statement
-------------------
It is requested for each audio, video, image, data, or web file, that you provide an appropriate license (e.g., CC-BY; see [also](https://creativecommons.org/licenses/)), prescribing your ownership and license for use of your media files.
Failure to do so will result in a de facto "no rights reserved" license granted to the instructor, the Center for Geospatial Analysis and William & Mary on all works submitted.

Please note that these media files may be reused for educational purposes on the course website, future Blackboard courses, or in a YouTube playlist.

You may contact the [CGA](mailto:cga@wm.edu) at any time to request that your media file(s) be no longer used.
