---
title: "The End of A Semester"
date: 2020-12-07
url: 2020-12-07-the-end-of-a-semester.html
summary: "Fall 2020 was like no other. My appreciation goes to all my students who muddled through yet another trying semester. Here's their feedback and what I plan to do about it next term."
---

We made it through a full (truncated) semester in one piece.
As I continue the redesign of my Advanced GIS course, it's good to hear what students had to say about this semester and see what changes I can make to improve the class for the coming term.

Below is a selection of comments that I received and I will do my best to respond.

> I think overall the course was fine but the one area that I personally had trouble with was the grading and teaching.
> This class did not follow the standard trend of showing up to lecture, learning material, doing a lab/project, and getting graded.
> Even though the grading system is not what usually happens in college, I think there is a lot of value to it since it more similarly reflects the real world and how we'd be "graded" in our jobs.
> For the instruction portion, I think the videos that you uploaded were very helpful but there's just something about learning directly from you rather than watching a prerecorded video that makes learning the material easier.
> Overall, I think the unorthodox nature of this class compared to most college classes wasn't a bad thing at all, especially since it prepares us more for the real world, but it wasn't exactly what I was expecting when I signed up for the course.

There's a little nuance to this critique.
The first is the teaching style, which is remote asynchronous and will not be directly from me; however, I am available every week to meet with students in office hours or during other scheduled appointments.
Yes, this moves the effort onto you the student to get that one-on-one contact.

I believe that college has an obligation to prepare students for the world after graduation and I don't see how the present course delivery (especially at the advanced levels) is successfully accomplishing this.
My motivation for change in course delivery and grading comes from experience and communication with those hiring newly minted college grads complaining about a lack of adherence to schedules, disrespecting superiors, attending meetings late, and expecting outcomes and solutions to be handed out or explained.

This grieves me.

I've reflected on my part as an educator and given serious thought to both what academia stands for (core pillars of knowledge) and what successful employment looks like after college.

With this class, I hope to bring some experiential learning and thought-provoking challenges that mimic the real world to help students be better prepared for what comes next.

> The format of this class was just not very clear, and the way our final grades are evaluated felt very ambiguous.
> If we exceeded the expectations in our final evaluation, this could result in a grade anywhere from a B+ to an A, with not much distinguishment about how to improve your grade within the bounds of "exceeding expectations".

I have two thoughts about this.

1. I think "ambiguity" here is misused.
    In my opinion, there is no ambiguity.
    I clearly state what each expectation is and what the requirement level is to fulfill each one.
    I clearly state the grades associated with each expectation level.

    If you think it's arbitrary, then welcome to education.
    As an educator, I am expected to set my own levels of expectations for student learning.
    This is what all educators are meant to do and it turns out to be a rather complicated process that I have yet to see perfected.
2. I give you the opportunity during the final evaluation to tell me where you think you stand.
    Self-evaluation is a powerful tool and everyone leaving my class this semester received at least the grade they expected to get.
    So what's the problem?

I appreciate that revealing the arbitrary nature of grade assignments may come as a shock to some, but if you think that point-based systems are any less arbitrary or less subjective or less quality based, then you are simply fooling yourself.

I don't like assigning grades any more than you like receiving them; however, by removing points from the equation, we can focus simply on the learning outcomes and whether or not you got what was expected.
We are now both fully responsible for what was delivered and what was gained.
There is no hiding behind extra credit, bonus points, or make-up work.

It's simple.

Did you do what was asked for?

If you didn't like it, then you are absolutely welcome to post your criticisms to the course evaluation and I will (just as I have done this semester) reflect on how to make the course better.

Your opinion matters to me!

> Given that this is a course still under development, I think it was relatively well done and will be a great course to take in the future.
>  I learned a lot about a lot of different topics, skills, and tools that I hadn't known anything about before the start of this semester.
> Professor Davis made himself available to students more than any other professor I have had---messages on groupme were always answered surprisingly fast!
> I appreciated that all of the assignments in the class were shaped to be practical and prepare us for using GIS in future careers. My biggest critique about the current presentation of the course is the organization.
> I think the syllabus laid out the expectations for the course nicely, but I would have appreciated it if more of the expectations/assignments had due dates, or ranges of time for expected completion, because everything felt a little too open-ended.

Okay, so moving straight passed the praise, the first critique is a lack of due dates.
This goes back to my philosophy for the class.
Due dates are not always the lunchbox of weekly lecture, assignments and grades.
Oftentimes, you will have to plan out several tasks over a longer period of time.
As an advanced GIS student, you already had the grindstone of working through long labs of instructions.
Now, the assignments are open-ended.
Put your knowledge to the test and, if you get stuck, consult with your peers.


> It was also difficult to keep track of all the different platforms we used to engage with the class (Prof. Davis's blog, the syllabus, the CGA site, Blackboard, the Youtube channel, Zoom, Nooks, the shared google folder, AGOL, groupme, etc).
> I felt like I had to be constantly checking in with all of these different locations to make sure I was able to keep up and engage.

Yeah, that's on me.
I have not found a great "all-in-one" solution for organizing this course.
I personally don't like Blackboard, so I try to steer away from it when I can.
During the summer of 2020, I tried GitHub teams, which was somewhat successful, but there were other challenges that term, which we can get into elsewhere on this blog.

I try to make it clear that each outlet has its purpose:

* GroupMe is an instant messaging platform that logs all communication in our group and provides instant outreach and feedback to everyone.
    It's primary purpose is for quick messaging.
* My blog was originally created in the Fall of 2019 because I asked my students to keep a blog for the class and I told them I would also do everything I asked them to do---a shared learning experience.
    This blog now serves as a place of reference.
* The syllabus is an academic document required by law.
    It serves as the foundation of our agreement and is used to guide all decisions within a given semester.
* The CGA site is the course website.
    It hosts a link to syllabus, my blog, and my lecture slideshows.
* The YouTube channel is actually just a playlist of tutorials, lectures and demos.
    It's a bit of a mess, but I am trying to structure these videos in a more logical series that is easier to follow and work through.
* Zoom is the video conferencing platform to be used for our one-on-one meetings and final evaluation.
* Nooks is a new Zoom alternative that provides a virtual space for collaborating.
    I also use this for my office hours.
    It is not Safari nor mobile friendly (at this time) and for that I apologize.
* The Google shared folder is a repository for your work.
    I meant for it to be an easy way to upload all assignments, datasets, articles, etc. so that nothing got lost.
* Our AGOL shared group was meant for easy sharing of spatial data, notebooks, and other web resources.

I see now that there are too many places for things.
Moving forward, I will choose one as the primary place where all communication and records are kept and, from there, link out to the other resources.

So what is the best central location for course content delivery?


> I was not prepared for the focus on Notebooks/Python that the course seemed to expect.
> At the beginning of the semester I spent far too much time anxiously trying to figure out how to use Notebooks for fear I wouldn't pass the class otherwise.
> I think it is definitely a great tool to know, but maybe in the future either emphasize that you don't *have to* use notebooks, or make a coding class a pre-requisite for the class.

Okay, so I'm not going to make coding a pre-requisite for this class.
Yes, ambition got the better of me and I focused a lot more on the data science side (I am a Data Science faculty after all).

The reason I cared so much is that Notebooks provides the equity for accessing ArcGIS geoprocesses that has been missing for so long.
Finally, a cloud-based ArcGIS!
The catch is, you have to know your way around Python to use it.

This review is right.
Python is necessary to take advantage of Notebooks.

With that in mind, I have decided to implement a focus option for the class:

* Advanced Analysis: focus more on geoprocessing tools and problem solving regardless of platform/software; though, I will push you to use ModelBuilder and see how automation and programming can assist you in geospatial problem solving
* Advanced Programming: deep-dive into Notebooks for those comfortable using Python and see where this new tool can take you.
    There are a lot more data science majors/minors taking GIS courses and I am trying to be mindful of their experience and expectations without alienating those without a coding background.

I believe there is a lot both sides can learn from one another, which is why I encourage collaboration and teamwork.

> Most of the assignments were optional and highly structured around class collaboration which was really difficult because of the asynchronous structure.
> Although the point was to work on the projects that interested you.
> I found myself working on the assignments that were easy and I already had the skills to complete because they took the least amount of time.

This is true.

I rushed assignments from summer to fall becuase I had about five days to turn around between terms.
It was probably a placeholder that only one special works assignment was required, but I didn't change it in time, so I left it, as it didn't seem fair to change it after the course had begun.

For next term, I'm working on a way to better incentivize working through all the projects in something like a randomized final exam question.


> The class met synchronously every week, the meetings weren't necessary, but if you missed a meeting, there weren't notes and so there were aspects about projects that you would miss.

While this is not entirely true---I keep a spreadsheet with notes from every synchronous meeting---they are correct in that it probably wasn't a good choice.

So this came from last fall and summer semesters when students wanted more synchronous meetings.
I blindly agreed, but this directly contradicts the asynchronous class structure and disadvantages students taking the class specifically for this attribute.

Now, I see that we just need something to encourage contact / engagement each week.
I completed weekly reports all during grad school and for both my post-docs.
This is an invaluable tool and I plan to utilize this as a way to both keep students engaged (here's your weekly assignment) and encourage collaboration (everyone can see everyone else's reports) and time management (you can see where you stand amongst your classmates).

The weekly report can also serve as a medium for me to provide the much-requested feedback.


> It would have been helpful to have some classes that were more like lectures: explaining exactly what everything was doing.

Yes, I agree and I plan to make more lectures; however, due to the asynchronous nature of the class they will likely be videos, self-guided slideshows or assignments.


> This class also requires a lot of programming knowledge up front because
programming basics are not covered in the class.
> This class almost needs a prerequisite because of the level of programming needed to do well.

While I do introduce programming and I have revised my introduction with several activities / demos, I agree that I was overly ambitious presenting only solutions that utilize programming approaches.

As such, I plan to introduce two focus paths: analysis and programming.
The analysis path is more concerned about figuring out tools and introducing you to automation using ModelBuilder and some code.
The programming path pushes you directly into using code for solving geospatial challenges to see if you can achieve higher-level automation and efficiency.
