---
title: "The Jekyll"
date: 2020-02-03
url: 2020-02-03-the-jekyll.html
summary: "The failed attempts of using Jekyll as a simple blogging site begins. What have I gotten myself into?"
---

> Jekyll, thou art a villainous foe.

In all good intentions, I had planned that we utilize the "simple blogging site" that is Jekyll and GitHub Pages for communicating the learning objectives of this class.
Little did I know, that Jekyll sites are truly miserable to get a handle on.
Despite all the resources I have found, there are no good "starting a blog site" instructions for this pairing.
The Jekyll help pages are simply that, help pages---no tutorials or templates.

My goals:

* only use markdown rather than HTML (**failed**)
    - you have to create at least one HTML file (i.e., the default.html in \_layouts directory)
* have Jekyll static site generator handle all the style (**failed**)
    - Jekyll themes seem to require a style.scss in assets/css, which you don't realize you need until you go to the theme's GitHub page
    - in my opinion, a modern-day website should include a navigation bar, which Jekyll seems to omit with its themes (I chose the theme [slate](https://github.com/pages-themes/slate)).
* simply upload blog posts that are automatically rendered to my website (**failed**)
    - to get blog posts on to your website, you have to design a web page and somehow link to your post content, which is not entirely clear

Overall, I am washed with a feeling of dissatisfaction.
