---
title: "Reproducibility"
date: 2021-02-02
url: 2021-02-02-reproducibility.html
summary: "Happy Groundhog's Day. Yay! More winter. Here's the low-down on Client Meeting progress reports on the reproducibility of published geoprocesses. This will be updated each semester, so check back to see how it's going."
---

***

A part of the Advanced GIS course consists of student-led consultancies, who are examining the state of the literature by identifying an article published by a reputable journal within the last 20 years to see if the geospatial methodology is reproducible to the best of their abilities.

Consultancies are listed in the table below along with the article under review and one of three grades determined by the teams members.
Links to consultancy websites provide more information on the article background, data and methods.

:   Table 1. Reproducibility results. Links the project papers and team websites (where available).

| Term  | Project                   | Team              | Grade |
| :-----| :------------------------ | :---------------- | :---: |
| Fall 2021 | ["High-resolution prediction of American red squirrel in Interior Alaska: a role model for conservation using open access data, machine learning, GIS and LIDAR"][robold-huettmann-21] | [Atlas][atlas] | TBA |
| Fall 2021 | ["A Comparative Assessment of Food Deserts Using Geographic Information Systems (GIS) in El Paso County, TX and Loudoun County, VA"][raysoni-18] | [Carto Consulting][carto-consult] | TBA |
| Spring 2021 | ["Mapping Land Use Land Cover Change in the Lower Mekong Basin From 1997 to 2010"][spruce-20] | [VPRSC][vprsc] | S |
| Fall 2020 | [Geology and Wine 8. Modeling Viticultural Landscapes:  A  GIS Analysis  of  the  Terroir Potential  in  the  Umpqua Valley of Oregon][jones-04] | Dorian and Haley | S |
| Fall 2020 | ["Infant and Child Mortality in India in the Last Two Decades: A Geospatial Analysis"][sing-11] | [Josh][habib] | S |
| Fall 2020 | ["GIS bio-waste assessment and suitability analysis for biogas power plant: A case study of Anambra state of Nigeria"][chukwuma-21] | [Maeve and Sam][maeve-sam] | S |
| Fall 2020 | ["Using a geographic information system to enhance patient access to point-of-care diagnostics in a limited-resource setting"][ferguson-16] | Jerry, Mayada, and Sean | S |
| Spring 2021 | ["Forest Fire Risk Assessment Using Hotspot Analysis in GIS"][said-17] | [First Ascent Spatial Solutions][first-ascent] | M |
| Spring 2021 | ["The Effects of Historical Housing Policies on Resident Exposure to Intra-Urban Heat: A Study of 108 US Urban Areas"][hoffman-20] | [Urban Thermal Taskforce][urban-thermal-taskforce] | M |
| Fall 2020 | ["Geographic access to gynecologic cancer care in the United States"][shalowitz-15] | Austin, Ciaran, and Amelia | M |
| Fall 2020 | [Least cost path analysis of early maritime movement on the Pacific Northwest Coast][gustas-17] | [Kat and RJ][kat-rj] | M |
| Fall 2020 | ["Modelling future landscape change on coastal floodplains using a rule-based GIS"][brown-06] | [Lindsey and Sarah Grace][lindsey-sarah-grace] | M |
| Fall 2020 | ["Towards the development of a GIS method for identifying rural food deserts: Geographic access in Vermont, USA"][mcentee-10] | [Caroline and Lauren][lauren-caroline] | M |
| Spring 2021 | ["A GIS-based method for the selection of the location of residence"][albacete-12] | [Geo-Problem Solvers][geo-problem-solvers] | U |

[albacete-12]: https://doi.org/10.1080/10095020.2012.708159
[atlas]: https://sites.google.com/email.wm.edu/atlas-consultancy/overview
[brown-06]: https://doi.org/10.1016/j.envsoft.2005.07.011
[carto-consult]: https://cartoconsulting.weebly.com/
[chukwuma-21]: https://doi.org/10.1016/j.renene.2020.09.046
[ferguson-16]: http://doi.org/10.1186/s12942-016-0037-9
[first-ascent]: https://sites.google.com/email.wm.edu/first-ascent/home
[gustas-17]: http://dx.doi.org/10.1016/j.jas.2016.11.006
[habib]: https://sites.google.com/email.wm.edu/joshuahabib/client-meeting/purpose-and-key-concepts?authuser=0
[hoffman-20]: http://dx.doi.org/10.3390/cli8010012
[jones-04]: https://journals.lib.unb.ca/index.php/GC/article/view/2779/3267
[kat-rj]: https://sites.google.com/email.wm.edu/marine-lcp-analysis/overview
[lauren-caroline]: https://storymaps.arcgis.com/stories/9379895103e34c0aafc922ed57d0cba3
[lindsey-sarah-grace]: https://sites.google.com/email.wm.edu/client-meeting/home
[maeve-sam]: https://storymaps.arcgis.com/stories/bbf8d416c924465aa137b546dbcb1921
[mcentee-10]: https://doi.org/10.1016/j.apgeog.2009.05.004
[raysoni-18]: https://digitalcommons.utep.edu/open_etd/1525
[robold-huettmann-21]: https://doi.org/10.7717/peerj.11830
[said-17]: http://dx.doi.org/10.2174/1874149501711010786
[shalowitz-15]: https://doi.org/10.1016/j.ygyno.2015.04.025
[sing-11]: https://doi.org/10.1371/journal.pone.0026856
[spruce-20]: https://doi.org/10.3389/fenvs.2020.00021
[geo-problem-solvers]: https://sites.google.com/email.wm.edu/geoproblemsolving-gis420/home
[urban-thermal-taskforce]: https://urbanthermaltaskforce.weebly.com/
[vprsc]: https://vprsc.weebly.com/

***

### Grades

S
:   Satisfactory (methods are clear and reproducible).

M
:   Marginal (it is hard to say because some methods are unclear and/or data are outdated or not readily available).

U
:   Unsatisfactory (there is no way to reproduce these methods)
