---
title: "Advanced GIS Analysis &amp; Programming"
pagetitle: "Advanced GIS"
author: Center for Geospatial Analysis
---

****

```{r echo=FALSE, results='asis', comment=NA}
# Print the current date (based on local computer time)
cat("Updated:", as.character(Sys.Date()))
```

This course extends the existing base of GIS knowledge and skills by amplifying programmatic approaches to spatial data and analysis.
Lectures, labs, and projects emphasize GIS model development, develop spatial database architecture and design best practices, and extend knowledge of web GIS by authoring and consuming geographic web services.
Students will become familiar with methods of leveraging programming languages (such as Python) to make GIS processing easier, faster, and more accurate by scripting and automating data management, production, manipulation, and analysis procedures.
Activities develop GIS analysis skills with examples from government, social science, physical science, and the humanities.

- [Course Syllabus (Spring 2020)](https://drdavis.space/teaching/gis/cga-adv/syllabus/2020/spring/)
