---
title: "Risk Assessment"
author: "The Landslide Analysis Project"
---

***

- Performance Accomplishments ([.docx][padocx]) ([.gdoc][pagdoc]) **&#8592; please email completed form to professor by 9 AM on 23 March 2020**
- Performance Review Worksheet ([.docx][prwdocx]) ([.gdoc][prwgdoc])
- Evaluation Sign-Up Sheet ([.gdoc][esus1])
- Group Sign-Up Sheet ([.gdoc][gsus1])

Landslides may occur in every country of the world and impact every aspect of the human condition from public health; property value, taxes, and insurance; government spending, national aid, and political agendas; ethics, economics and social inequality; to hazard identification, mitigation, science and research.

In this first scenario, you work for an organization that has tasked you, the GIS experts, to sort out landslide susceptibility for several international clients.

You, members of our organization, will break into teams (undergrads in teams of 2--3 and graduates/certificate students as individuals or pairs) and will be assigned international clients (chosen at random, see [the Python script (.py)](scripts/random_country_generator.py)).
Your team will create its own consultant firm (with a name, slogan, logo, etc.) and have a web presence (e.g., using GitHub Pages) to communicate your tasks and accomplishments to your organization's management and the clients.

***

## Consultants

| Team              | Members               | Countries                       |
| ----------------- | --------------------- | ------------------------------- |
| [HAM Landslide Analysis][HAM] | Matt, Alexa, and Henry | France, Egypt, Gibraltar, and the USA |
| [Tunis Disaster Analysis](https://tunisda.weebly.com/) | Ian, Morgan, and Michele | Mayotte, Tunisia, the British Indian Ocean Territory, and the USA |
| [Edgeworth Consulting](https://edgeworthconsulting.weebly.com/) | Erica and Victoria | the Marshall Islands, Malaysia, Cuba, and the USA |
| [Dukes of Hazards](https://giraffename.github.io/) | Jeremy and Colleen | Bhutan, Sint Maarten (Dutch part), Latvia, and the USA |
| [Unstable Land Consulting](https://unstable-ground-consulting.github.io/Landslide-Susceptibility/) | Jake | Nauru, Albania, Belize, and the USA |
| [Slope Consulting](https://slopeconsulting.github.io/) | Sean | French Polynesia, Bahrain, Jordan, the USA |
| [Mola Mola consulting](https://molamolaconsulting.github.io/) | Jesus and Tate | Somalia, Estonia, Mozambique, and the USA |

[HAM]: https://hamlandslideanalysis.weebly.com/

***

## The Susceptibility Model
The Critical Rainfall Threshold Model (Eq. 28, [Iverson, 2000](https://doi.org/10.1029/2000WR900090)) is given by $F_s = F_f + F_c - F_w$, which may be expressed by the following.

$$
F_s = \frac{\tan \phi}{\tan \theta} + \frac{C}{\gamma_r * H * \sin \theta * \cos \theta} - \frac{\psi_t * \gamma_w * \tan \phi}{\gamma_r * H * \sin \theta * \cos \theta}
$$

where:

- $F_s$ is the factor of safety
- $\phi$ is internal angle of friction (deg)
- $\theta$ is hillslope (deg)
- $C$ is soil cohesion (Pa = kg/m/s^2)
- $\psi_t$ is pressure head (m) (Eq. 6, [Gabet et al., 2004](https://doi.org/10.1016/j.geomorph.2004.03.011))
- $\gamma_w$ is unit weight of water (N/m^3); N=kg*m/s^2
- $\gamma_r$ is unit weight of soil regolith (N/m^3)
- $H$ is soil regolith thickness (m)

[esus1]: https://docs.google.com/spreadsheets/d/1_0FP0fRHuniI3wL1UyGTFopvj-Hi6Y4RPPkbMHkJyY0/edit?usp=sharing
[gsus1]: https://docs.google.com/spreadsheets/d/12JU9kP3h-AxnYTQ94clRRjTtgdyHwLhPzryoLE5TNO4/edit?usp=sharing
[prwdocx]: docs\GIS420-520_S20_PRW-1.docx
[padocx]: docs\GIS420-520_S20_PA-1.docx
[prwgdoc]: https://docs.google.com/document/d/1Imlo0qUh7pSh2pn_6FOhjprq35SD2munp1YMLrpBoV0/edit?usp=sharing
[pagdoc]: https://docs.google.com/document/d/1g5FgJ4xieyl9dPvzktkNZMOetml7QIT98QlhhxXlsXk/edit?usp=sharing

***

## An Example Project Outline

1. Select a city or town from one of your assigned countries
1. Create a base map of your town/city
    - Include information relevant to hazard analysis (e.g., properties, roads, utilities, and other critical infrastructure); consider what information you include and what information you exclude (candidate for your ethics discussion)
    - Create new spatial data (e.g., geocoding, georeferencing); this is candidate for your 'how-to'
1. Find elevation data for your study area
    - do a little research to determine whether your elevation data is a DEM, DTM, or DSM
    - try examining more than one DEM for your study region and analyze their differences; which is the better candidate and why?
    - calculate slopes based on elevation
1. Find soil maps of your study region; you may have to go to the library for paper versions if online maps are not available (luckily, the library is conveniently located)
    - rasterize soil maps (if necessary)
    - classify soil maps for cohesion and friction angle values; this may end up being a raster of one value for the whole study area
1. Research soil depth and average to maximum rainfall events for your study area; use these values in your susceptibility model
1. Assemble a geoprocessing workflow (e.g., model builder, python script, or toolbox) for the susceptibility model given above; another candidate for your 'how-to'
1. Overlay susceptibility with your base map to identify at-risk infrastructure
1. Simulate a landslide by artificially increasing the land surface elevation in areas of susceptibility to emphasize risk to your client
1. Repeat for any additional cities you have time for

***

## References

**Websites**

- [How to setup a GitHub Organization, project and team](https://github.com/collab-uniba/socialcde4eclipse/wiki/How-to-setup-a-GitHub-organization,-project-and-team)
- [Creating GitHub Pages site](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site)
- [Creating and Hosting a Personal Site on GitHub](http://jmcglone.com/guides/github-pages/)
- [Simple navigation menus in Jekyll](https://learn.cloudcannon.com/jekyll/simple-navigation/)
- [Jekyll's directory structure](https://jekyllrb.com/docs/structure/)


**Landslides**

* Emergency Management Framework: The Context of Disasters [Ch 3.1](https://www.nap.edu/read/11793/chapter/5)
* The Physical Factors of Landslides by Hall & Walker, 2017  [(pptx)](https://d32ogoqmya1dw8.cloudfront.net/files/getsi/teaching_materials/surface_processes/unit_3_physical_factors.v6.pptx)
* Material Strength and Landsliding Assessment by Hall & Walker, 2017 ([pptx](https://d32ogoqmya1dw8.cloudfront.net/files/getsi/teaching_materials/surface_processes/unit_3_strength_assessment.v12.pptx))
* [Landslides \| National Geographic]( https://youtu.be/mknStAMia0Q)
* [When Nature Strikes - Landslides](https://youtu.be/dj44dpr8oHs?t=18)
* [Mount St. Helens Disintegrates in Enormous Landslide](https://youtu.be/UK--hvgP2uY)


**Programming**

* [Geoprocessing with Python; Ch. 2](https://livebook.manning.com/book/geoprocessing-with-python/chapter-2/1). Garrard, 2016.
* [Creating a new Python toolbox](https://pro.arcgis.com/en/pro-app/arcpy/geoprocessing_and_python/creating-a-new-python-toolbox.htm)


***

## The Consultants Meeting
* __When__: Monday, 23 March 2020
* __Where__: CGA
* __Who__: Everyone
* __Why__: All consultant groups are to meet to discuss the state of their work including any results, conclusions, challenges, and setbacks with their client (played by a bonafide CGA Fellow). This is a real-world simulation of a client meet, so please be professional and respectful. You can expect that the client will report back to your professor.

    Just as you would meet with a real client, you should have materials prepared for the client to look at (e.g., a report with figures/tables/graphs). You may ask your client to go to your website or visit web materials, such as a presentation or report file (add link to the group sign-up sheet). You should _not_ expect the client to have ArcGIS software or know how it works. Remember, you are the GIS expert.

    During this time, you will also be meeting with your professor to review your Performance Accomplishments (see sign-up sheet); time is limited, so please have your materials ready prior to meeting.

***
