---
title: "Ethics Assessment"
author: "The Electioneering Project"
---

# {.tabset}

## Overview

- Performance Accomplishments ([.gdoc][pagdoc]) **&#8592; please email completed form to professor 24 hours before evaluation**
- Performance Review Worksheet ([.gdoc][prwgdoc])
- Evaluation Sign-Up Sheet ([.gdoc][esus1])

You have been hired as a GIS expert to consult in analyzing geospatial data associated with Election 2020 for the new president of the United States.

Questions have arisen regarding the geoethics of the election process (i.e., electioneering).
Your goal is to either strengthen or weaken the argument that there are any prejudices or discriminatory practices taking place regarding the election.

For this project, you will keep an ArcGIS Notebook [(pdf)](https://community.esri.com/servlet/JiveServlet/downloadBody/13764-102-3-22953/agol_notebooks.pdf) of your findings and analyses.
You will save/export your notebook as an HTML document to be shared across the web with your client.
In order to accomplish this task, you will need to learn [Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) and Python scripting in a Jupyter notebook style setting, for which this class will prepare you.



***

### Consultants

| Team              | Members               |
| ----------------- | --------------------- |
| TBA | TBA |


***


[esus1]: #
[prwgdoc]: #
[pagdoc]: #

***

### An Example Project Outline
TBA

***

### The Consultants Meeting
* __When__: TBA
* __Where__: Zoom
* __Who__: Everyone
* __Why__: All consultants are to meet to discuss the state of their work including any results, conclusions, challenges, and setbacks with their client (played by a bonafide CGA Fellow). This is a real-world simulation of a client meet, so please be professional and respectful. You can expect that the client will report back to your professor.

    Just as you would meet with a real client, you should have materials prepared for the client to look at (e.g., a report with figures/tables/graphs). You may ask your client to visit web materials, such as a presentation or report file (add link to the group sign-up sheet). You should _not_ expect the client to have GIS software or know how it works. Remember, you are the GIS expert.

    During this time, you will also be meeting with your professor to review your Performance Accomplishments (see sign-up sheet) so please have your materials ready prior to meeting.

***

## Ice Breaker

## Election Data

## Analysis
