title: Advanced GIS Analysis and Programming
author: Tyler W. Davis
description: Taking GIS to the next level
theme: jekyll-theme-slate
show_downloads: False
google_analytics: False
markdown: kramdown
plugins:
    - jekyll-menus
