---
title: "Applications"
bibliography: refs.bib
---

> We cannot manage what we do not measure.&#8221;
>
> --- [Pavan Sukhdev](https://en.wikipedia.org/wiki/Pavan_Sukhdev), environmental economist

The power of GIS is its ability to answer certain types of questions, such as [@maguire91]:

- Locations (*What is at ...?*)
- Conditions (*Where is it ...?*)
- Trends (*What has changed ...?*)
- Routing (*Which is the best way ...?*)
- Patterns (*What is the pattern ...?*)
- Modelling (*What if ...?*)

Geographic Information Systems are sometimes categorized based on the questions they are used to address.
Some of these application-specific classifications include the following [@maguire91]:

- Cadastral information systems
- Image-based information systems
- Land data systems
- Geographically referenced information systems
- Natural resource management information systems
- Market analysis information systems
- Multipurpose cadastre
- Planning information systems
- Property information systems
- Soil information systems
- Spatial information systems
- Spatial decision support systems
- Urban information systems

One of the first major areas of GIS application was in natural resource management, which may include the management of some of the following [@footelynch95]:

- wildlife habitat
- wild and scenic rivers
- recreational resources
- floodplains
- wetlands
- agricultural lands
- aquifers
- forests

Other applications are also investigated below.

***

## Natural Disasters and Emergency Management

*Emergency management* is the organization and management of resources and responsibilities for dealing with all aspects of emergencies [@nrc07].
The four phases of emergency management include the following:

- preparedness
- response
- recovery
- mitigation

All disasters have a temporal and geographic footprint that identifies the duration of impact and its extent on the Earth's surface.
The term *geospatial* is used to refer to the interdependent resources---imagery, maps, data sets, tools, and procedures---that tie every event, feature, or entity to a location on the Earth's surface and use this information for some purpose.
Although location is an essential part of any item of geospatial data, it is the ability to link a location to the properties of events, features, or entities at that location that gives geospatial data their value.

***

## Watershed Delineation

DEM
:   Digital Elevation Map

Outlet
:   any point along a river, stream or creek; defines a unique watershed

Watershed
:   an area of land that drains all the streams and rainfall to a common outlet (also known as a drainage basin or catchment)

A watershed is the area of land where all of the water that falls in it and drains off of it goes to a common outlet.
Watersheds are important because the amount and the quality of water of a river are affected by things (e.g., human activity, pollution runoff, heavy rainfall), which are happening in the land area "above" the river-outflow point [@usgs16].

**Delineating a Watershed in GIS**

There are several ways to delineate a watershed; however, using standard GIS tools, the following are the basic steps for delineation.

Required spatial data:

- Elevation (raster) data; elevation or topographic data are required, which may be in the form of a digital elevation map (DEM) or other raster file format
- Outlet location; a watershed is defined by its outlet, which can be any point location along a river, stream or creek---typically, an outlet is defined at a critical juncture (e.g., where two rivers meet) or just upstream of a city or town (e.g., for flood management)

Geoprocessing tools:

- fill sinks
- calculate flow direction
- calculate flow accumulation
- define the pour point
- delineate the watershed

***

## Habitat Suitability

Habitat suitability rank
:   identification of potential living areas based on various grades of suitability criteria

Habitat suitability
:   identification of optimal living areas based on a set of suitability criteria

***

## Geostatistics
As a discipline, geostatistics was firmly established in the 1960s by the French engineer [Georges Matheron](https://en.wikipedia.org/wiki/Georges_Matheron), who was interested in the appraisal of ore reserves in mining.

Geostatistics did not develop overnight.
Like other disciplines, it has built on previous results, many of which were formulated with different objectives in various fields.

Seminal ideas conceptually related to what today we call geostatistics or spatial statistics are found in the work of several pioneers, including:

* 1940s: [Andrey N. Kolmogorov](https://en.wikipedia.org/wiki/Andrey_Kolmogorov) in turbulent flow and [Norbert Wiener](https://en.wikipedia.org/wiki/Norbert_Wiener) in stochastic processing
* 1950s: [Danie G. Krige](https://en.wikipedia.org/wiki/Danie_G._Krige) in mining
* 1960s: B. Mathern in forestry and L.S. Gandin (Russian) in meteorology

Most geological phenomena are extraordinarily complex in their interrelationships and vast in their geographical extension.
Ordinarily, engineers and geoscientists are faced with corporate or scientific requirements to properly prepare geological models with measurements involving a significantly small fraction of the entire area or volume of interest.
Exact descriptions of such systems are neither feasible nor economically possible and therefore the results are necessarily uncertain.
It should be noted, however, that **uncertainty is not an intrinsic property of the systems**, rather it is the result of the incomplete knowledge of the observer.[@olea09]

The main objective of geostatistics is the characterization of spatial systems that are incompletely known.

Geostatistics makes use of a collection of numerical techniques for the characterization of spatial attributes using primarily two tools:

* probabilistic models
* pattern recognition techniques

The probabilistic models are used as a way to handle uncertainty in results away from sampling locations, making a radical departure from alternative approaches like inverse distance estimation methods.


## References
