---
title: "Resources | General Info"
---

***

[ArcGIS Tutorials](https://mgimond.github.io/ArcGIS_tutorials/index.html)

[Do you know where you are? - The Global Positioning System](https://oceanservice.noaa.gov/education/tutorial_geodesy/geo09_gps.html). National Oceanic and Atmospheric Administration (NOAA). 2017.

[Documentation for ArcGIS](https://doc.arcgis.com/en/)

[GIS Certification Institute](https://www.gisci.org) --- a non-profit organization that provides the GIS community with a complete certification program leading to Certified GIS Professional recognition focused on six key knowledge areas: *Conceptual Foundations*, *Cartography and Visualization*, *GIS Design Aspects and Data Modelling*, *GIS Analytical Methods*, *Data Manipulation*, and *Geospatial Data*

[Geography Realm](https://www.geographyrealm.com/) --- an information site about all things geography (formerly Geo Lounge). Find information here about physical and human geography as well as guides for learning about geography and developing a career in geography.

[Geography & Map Reading Room](https://www.loc.gov/rr/geogmap/index.html) --- The Geography and Map Division of the Library of Congress provides cartographic and geographic information for all parts of the world to the Congress, Federal agencies, state and local governments, the scholarly community, and to the general public; it is the largest and most comprehensive cartographic collection in the world, numbering over 5.2 million maps.

[GIS Lounge](https://www.gislounge.com/) --- news, data and information on GIS

[GPS: An Introduction to Satellite Navigation](https://www.youtube.com/playlist?list=PLGvhNIiu1ubyEOJga50LJMzVXtbUq6CPo) ("GPS MOOC"). Stanford University. 2014.

[Living Atlas of the World](https://livingatlas.arcgis.com/) --- the foremost collection of global geographic information from Esri and its partners, including maps, apps, and data layers used to support critical decision making.

[Map Projections](http://geology.isu.edu/wapi/geostac/Field_Exercise/topomaps/map_proj.htm) --- Geospatial Training and Analysis

[Mapping our Changing World](https://www.e-education.psu.edu/geog160/) --- An e-class in geography by Xi Liu at Penn State University

[National Geospatial-Intelligence Agency](https://www.nga.mil)

[Projections and Coordinate Systems](https://courses.washington.edu/gis250/lessons/projection/)

[The Field Calculator Unleashed (pdf)](https://www.esri.com/news/arcuser/0405/files/fieldcalc_1.pdf)

[The GIS Encyclopedia](http://wiki.gis.com/wiki/index.php/New_to_GIS)

[The World Factbook](https://www.cia.gov/library/publications/the-world-factbook/docs/refmaps.html) --- Regional and world maps provided by the United States Central Intelligence Agency

[UNAVCO](https://www.unavco.org/unavco.html)
