---
title: "Resources | Additional Reading"
---

***

### Podcasts

[Esri and the Science of Where](https://www.esri.com/about/newsroom/podcast/) ---  this podcast is to help executives and leaders in the industry and government understand how modern GIS technology enables digital transformation and drives growth.

[Geodorable](http://cast.rocks/hosting/6022/feeds/1I9KO.html) --- by New Zealanders Chris Morris & Mark Thompson.

[VerySpatial](https://veryspatial.com/) --- your source for information on Geography and geospatial technologies.

***

### Online Articles and Textbooks

[Geographic Information Systems, First Edition, 1991](https://www.wiley.com/legacy/wileychi/gis/volumes.html) ---  Copyright &copy; John Wiley & Sons 1991. Converted to HTML by Jim Harper. Last updated January 16, 2001.

[Geometric Aspects of Mapping](http://kartoweb.itc.nl/geometrics/index.html) --- provides information on concepts of spatial referencing, including a brief introduction followed by more in-depth notes on coordinate systems, reference surfaces, map projections and coordinate transformations. International Institute for Geo-Information Science and Earth Observation (ITC), Enschede, 2009.

[GIS as an Integrating Technology](https://foote.geography.uconn.edu/gcraft/contents.html) --- materials by Kenneth E. Foote and Margaret Lynch, The Geographer's Craft Project, Department of Geography, The University of Colorado at Boulder. Copyright 2000--2015.

[GPS: The Global Positioning System](https://www.gps.gov/). Maintained by the National Coordination Office for Space-Based Positioning, Navigation, and Timing. 2018.

[GPS Basics](https://learn.sparkfun.com/tutorials/gps-basics). Written by Aaron Weiss (a1ronzo). Available online at SparkFun Electronics. Accessed 18 January 2018.

[GPS Tutorial](http://www.trimble.com/gps_tutorial/). Trimble Inc. 2018.

[Intro to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html) --- a compilation of lecture notes into an online textbook on data manipulation & visualization and exploratory spatial data analysis by Manuel Gimond

[Johannes Kepler: His Life, His Laws and Times](https://www.nasa.gov/kepler/education/johannes). National Aeronautics and Space Administration (NASA). 2017.

[The Global Positioning System](https://foote.geography.uconn.edu/gcraft/notes/gps/gps_f.html). Written by Peter H. Dana, Department of Geography, University of Texas at Austin. 1994. Provided by Ken Foote, The Geographer's Craft, Department of Geography, University of Colorado at Boulder. 2015.

[The Nature of Geographic Information](https://www.e-education.psu.edu/natureofgeoinfo/) --- an open-access textbook to promote understanding of the Geographic Information Science and Technology enterprise.
